server:
  port: 8080
  servlet:
    context-path: /
spring:
  datasource:
    druid:
#      url: jdbc:mysql://192.168.221.128:3306/world?useUnicode=true&characterEncoding=utf-8&useSSL=false
#      username: root
#      password: 123456
      url: jdbc:mysql://10.1.10.41:43306/ehrealty?useTimezone=true&serverTimezone=Asia/Shanghai&characterEncoding=UTF-8
      username: root
      password: 6%3aogdP6YhAG3B
      driver-class-name: com.mysql.cj.jdbc.Driver
      initial-size: 30
      max-active: 100
      min-idle: 10
      max-wait: 60000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 1 FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      filters: stat,wall
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    auto-mapping-behavior: full
  mapper-locations: classpath*:mapper/**/*Mapper.xml